# Data representation for neural networks



#### we started from data stored in multidimensional Numpy arrays, also called tensors.


## 1. Scalars (0D tensors)

A tensor that contains only one number is called a scalar (0-dimensional) tensor.
In Numpy ,a float32 or float64 number is a scalar tensor or scalar array. You can display the number of axes of a Numpy tensor via the ndim attributes ; a scalar tensor has 0 axes (ndim==0). 
### The number of axes of a tensor is also called its rank.

## Here's a Numpy scalar:

In [2]:
import numpy as np
x= np.array(12)
x

array(12)

In [3]:
x.ndim

0

## 2. Vectors(1D tensors)

An array of numbers is called a vector, or 1D tensor. A 1D tensor is said to have exactly one axis.

## Numpy vector:

In [4]:
x = np.array([12,34,11,4])
x

array([12, 34, 11,  4])

In [5]:
x.ndim

1

## 3. Matrices(2D tensors)

An array of vectors is a matrix, or 2D tensor. A matrix has two axes(often referred to rows and columns).

## Numpy matrix:

In [6]:
x=np.array([[5,15,34,5],[3,5,2,16],[2,4,5,67]])
x

array([[ 5, 15, 34,  5],
       [ 3,  5,  2, 16],
       [ 2,  4,  5, 67]])

In [7]:
x.ndim

2

## 4. 3D tensors and higher dimensional tensors

## Numpy 3D tensor:

In [14]:
x=np.array([[[5,7],[2,3],[5,1]],[[2,4],[1,2],[2,5]],[[2,1],[2,4],[4,5]]])
x

array([[[5, 7],
        [2, 3],
        [5, 1]],

       [[2, 4],
        [1, 2],
        [2, 5]],

       [[2, 1],
        [2, 4],
        [4, 5]]])

In [16]:
x.ndim

3

### Note: In the context of tensors , a dimension is often called axis.

# **Key attributes
### A tensor is defined by three key attributes:
####  1.Number of axes(rank)
####  2.Shape
####  3.Data type

In [17]:
print(x.ndim)

3


In [18]:
print(x.shape)

(3, 3, 2)


In [20]:
print(x.dtype)

int32
